name: GitHub action prepare for pipeline in Java

on: 
  push:
    paths:
    - '**'

jobs:
  Default:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main
  
    ############# Prepare #############
   
    - name: Install powershell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install mvn
      run: |
        sudo add-apt-repository ppa:webupd8team/java
        sudo apt-get update -y
        sudo apt-get install oracle-java8-installer
        cd /opt/
        wget http://apache.mirrors.pair.com/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
        sudo tar -xvzf apache-maven-3.6.3-bin.tar.gz
        sudo mv apache-maven-3.6.3 maven 

    - name: verify install
      run: |
        mvn --version
      